name: Unseen
version: 1.2
main: me.Unseen.Unseen
api-version: 1.21.8
author: [nobstergo]
contributors: [alprny]
depend: [ProtocolLib]
commands:
  unseen:
    description: Unseen plugin main command7
    usage: /unseen <subcommand>
    permission: unseen.use
permissions:
  unseen.admin:
    description: Admin permissions for reload & config editing
    default: op